### ISSUE TITLE
Can't this be put in a normal vue component??

### ISSUE THREAD

**Issue by Issabln** [ErickPetru/vue-feathers-chat#1]

**Comment by ErickPetru** [comment]
Sure, it can. Since the Feathers' `public` directory is the default static content sent to the browser, I took advantage of it to simplify the solution. But an easy and common approach would be separate the frontend Vue project of the backend Feathers project. Another approach would be adjusting the `index.js` to generate the client bundle with Webpack/Babel, as you can found in many Vue projects with Express.
